### ISSUE TITLE
What is different in the plugin from phinx

### ISSUE THREAD

**Issue by abuzer-firdousi-confiz** [beezee/wp-phinx#1]
It seems to be the same clone of phinx repository?

Can we track the delta changes in the database for the WordPress post creation/update/delete post meta saving plugin activation etc?

**Comment by beezee** [comment]
Thanks for your interest. to be completely honest with you it's been 4.5 years since I looked at this code, and at least as long since I thought about WordPress or PHP. 

I can't remember what my use case for this was, but the answer to your first question is possible to reconstruct from the commits I've added to this repo. Specifically https://github.com/beezee/wp-phinx/commit/fdc1100d37733f711325fa890cc86fc8d4f77d25 seems to have some clues in it.

The answer to your second question is definitely no.

And not that you asked, but I certainly do not recommend using this code, if not for the fact that it is PHP and deals with WordPress, then at least for the fact that it was something I thought about on May 3 2014, and probably not really much at all any time after that.
